"""
Class for reads. Each read is described by a name, start position, end position, quality array, mutations, errors,
and whether it is on the reverse strand.

In addition, we attach the reference sequence for later retrieval.

Methods allow comparisons between reads, based on chromosome, start and end. Also, there are methods to retrieve
both the reference sequence and the read and the actual read sequence.
"""
import logging
from copy import deepcopy

import numpy as np

from typing import TextIO, Iterator
from Bio.Seq import Seq, MutableSeq
from Bio.Align import PairwiseAligner
from numpy.random import Generator

from ...common import ALLOWED_NUCL, NUC_IND
from ...models import SequencingErrorModel, ErrorContainer, TraditionalQualityModel
from ...variants import SingleNucleotideVariant, Insertion, Deletion

_LOG = logging.getLogger(__name__)


class Read:
    """
    A class representing a particular read

    :param name: name for the read
    :param raw_read: gives the read as a tuple of coordinates, e.g., (1, 110, 111, 125)
        Which gives information about the left and paired right read, or gives 0,0 for missing component
    :param reference_segment: The reference segment this read is drawn from
    :param reference_id: the ID for the reference where the segment is drawn from
    :param position: First position of the read, relative to the reference
    :param end_point: End point of the read, relative to the reference
    :param padding: The amount of padding we have for this read, will influence if we can add deletions
    :param run_read_len: The final read length desired.
    :param is_reverse: Whether the read is reversed
    :param is_paired: Whether this read has a proper pair.
    :param genomic_len: How many of the read's bases come from the reference. Equals run_read_len for
        an ordinary read; smaller when the insert was shorter than the read length and the 3' tail is
        adapter. Defaults to run_read_len.
    :param adapter_seq: The 3' sequencing adapter to read through into, in FINAL read orientation
        (i.e. already accounting for the reverse complement applied to read 2). Empty string, the
        default, disables readthrough entirely.
    """
    def __init__(self,
                 name: str,
                 raw_read: tuple,
                 reference_segment: Seq,
                 reference_id: str,
                 ref_id_index: int,
                 position: int,
                 end_point: int,
                 padding: int,
                 run_read_len: int,
                 segment_start: int = None,
                 is_reverse: bool = False,
                 is_paired: bool = False,
                 genomic_len: int = None,
                 adapter_seq: str = ""):

        self.name = name
        self.raw_read = raw_read
        # This segment will gold the raw read and be untouched.
        self.reference_segment = reference_segment
        self.reference_id = reference_id
        self.ref_id_index = ref_id_index
        self.position = position
        self.end_point = end_point
        self.padding = padding
        self.run_read_length = run_read_len
        # segment_start is the reference coordinate of reference_segment[0], which may be
        # earlier than self.position for reverse reads (padding prepended for deletion headroom).
        self.segment_start = segment_start if segment_start is not None else position
        self.is_reverse = is_reverse
        self.is_paired = is_paired
        # Bases drawn from the reference. Only differs from run_read_length when the insert was
        # shorter than the read, in which case the remainder is adapter (see
        # _append_adapter_readthrough). Everything reference-derived — the quality array the error
        # model sees, mutation application, the M/I/D part of the CIGAR — is sized by this.
        self.genomic_length = genomic_len if genomic_len is not None else run_read_len
        self.adapter_seq = adapter_seq
        # Zero unless there is both a shortfall to fill and an adapter to fill it with, which
        # makes every adapter branch below a no-op for an ordinary read.
        self.adapter_length = max(0, run_read_len - self.genomic_length) if adapter_seq else 0

        # These parameters won't be initialized on the initial read creation, but will
        # be generated by functions below.
        self.read_sequence: Seq = Seq("")  # initialize to empty sequence
        self.errors: list[ErrorContainer] = []  # initialize
        self.mutations: dict[int, list] = {}  # initialize
        self.quality_array: np.ndarray = np.zeros(self.genomic_length, dtype=int)  # this will have the correct memory length
        self.mapping_quality: int = 0  # initialize at 0
        self.read_quality_string: str = ""  # This will hold the read quality string
        self.num_ns = 0

    def __repr__(self):
        return f"{self.reference_id}: {self.position}-{self.end_point}"

    def __str__(self):
        return f"{self.reference_id}: {self.position}-{self.end_point}"

    def __gt__(self, other):
        if self.reference_id == other.reference_id:
            return self.position > other.position
        else:
            return False

    def __ge__(self, other):
        if self.reference_id == other.reference_id:
            return self.position >= other.position
        else:
            return False

    def __lt__(self, other):
        if self.reference_id == other.reference_id:
            return self.position < other.position
        else:
            return False

    def __le__(self, other):
        if self.reference_id == other.reference_id:
            return self.position <= other.position
        else:
            return False

    def __ne__(self, other):
        if self.reference_id == other.reference_id:
            return self.position != other.position or self.end_point != other.end_point
        else:
            return True

    def __eq__(self, other):
        if self.reference_id == other.reference_id:
            return self.position == other.position and self.end_point == other.end_point
        else:
            return False

    def __len__(self):
        return self.run_read_length

    def update_quality_array(
            self,
            ref_length: int,
            alternate: Seq,
            location: int,
            variant_type: str,
            quality_scores: list,
            quality_score: int = 0
    ):
        """
        This updates the quality score based on the error model. Uniform for mutations, random (but low) for errors
        :param ref_length: The length of the reference sequence for the variant
        :param alternate: The alternate sequence for the variant
        :param location: The first position of the mutation, in 0-based coordinates
        :param variant_type: Either "mutations" or "errors"
        :param quality_scores: The possible quality scores, used to adjust for mutations and errors
        :param quality_score: The quality score to use, since this has already been calculated for mutations.
            This must be included if type is 'mutation'
        :return: None, updates the quality array in place
        """
        if variant_type == "mutation":
            new_quality_score = [quality_score] * len(alternate)
        else:
            # Since we have an error here, we'll choose a min score
            low_score = min(quality_scores)
            # If is insertion
            if len(alternate) > 1:
                # Generate extra scores for insertions
                # Original ref is unaffected, so it's quality score remains the same
                new_quality_score = [low_score] * (len(alternate) - 1)
            # If is deletion
            elif ref_length > 1 and len(alternate) == 1:
                new_quality_score = []
            # SNP
            else:
                new_quality_score = [low_score]

        # Replace the given quality score with the new one
        self.quality_array = \
            np.concatenate((self.quality_array[:location],
                            np.array(new_quality_score, dtype=int),
                            self.quality_array[location+ref_length:]))

    def apply_errors(self, quality_model: TraditionalQualityModel):
        """
        Apply this read's stored sequencing errors to read_sequence and quality_array in
        a single pass.

        self.errors is in descending position order (set up by get_sequencing_errors).
        The original implementation iterated in that order, doing one np.concatenate +
        one MutableSeq slice/concat per error — quadratic in errors-per-read. Here we
        iterate ascending and append unchanged ranges plus error alternates into chunk
        lists, then join once at the end. The result preserves the prior per-error
        quality-array semantics (including the convention that insertion anchors lose
        their original quality and gain alt_len-1 low-quality scores).
        """
        if not self.errors:
            return

        errors_asc = list(reversed(self.errors))
        low_score = min(quality_model.quality_scores)

        seq_str = str(self.read_sequence)
        seq_chunks: list[str] = []
        q_chunks: list[np.ndarray] = []
        prev_end = 0

        for error in errors_asc:
            loc = error.location
            ref_len = len(error.ref)
            alt_str = str(error.alt)
            alt_len = len(alt_str)
            seq_chunks.append(seq_str[prev_end:loc])
            q_chunks.append(self.quality_array[prev_end:loc])
            seq_chunks.append(alt_str)
            if alt_len > 1:
                q_chunks.append(np.full(alt_len - 1, low_score, dtype=int))
            elif ref_len > 1 and alt_len == 1:
                pass  # deletion — no new quality scores
            else:
                q_chunks.append(np.array([low_score], dtype=int))
            prev_end = loc + ref_len

        seq_chunks.append(seq_str[prev_end:])
        q_chunks.append(self.quality_array[prev_end:])

        self.read_sequence = Seq(''.join(seq_chunks))
        self.quality_array = np.concatenate(q_chunks)

    def apply_mutations(self, quality_scores: list, rng: Generator):
        """
        Applying mutations involves one extra step, because of polyploidism. There may be more than one mutation
        at a given location, so it is formulated as a list. We then pick one at random for this read.

        :param quality_scores: The possible quality scores for this run (to update quality scores)
        :param rng: the random number generator for the run
        :return: mutated sequence, with mutations applied
        """
        mutated_sequence = MutableSeq(self.read_sequence)
        for location in self.mutations:
            variant_to_apply = rng.choice(self.mutations[location])

            # Fetch parameters
            qual_score = variant_to_apply.get_qual_score()
            # Find the position within the reference_segment for this variant. Use segment_start rather
            # than self.position because for reverse reads the segment begins padding bases before
            # self.position (leading padding for deletion headroom after reverse_complement).
            position = int(variant_to_apply.get_0_location() - self.segment_start)
            # Figure out if the variant is in this read. If 'to_mutate' selects any 1, then it is mutated.
            # For diploid animals, for example, this should result in approximately 50% of reads having a
            # given heterozygous mutation and 100% for homozygous mutations.
            to_mutate = rng.choice(variant_to_apply.genotype)
            # If a 1 was selected, then apply the variant, else return the original sequence
            if to_mutate:
                if type(variant_to_apply) == Insertion or type(variant_to_apply) == SingleNucleotideVariant:
                    reference_length = 1
                    alternate = variant_to_apply.get_alt()
                elif type(variant_to_apply) == Deletion:
                    reference_length = variant_to_apply.length
                    if self.padding - variant_to_apply.length < 0:
                        # Skip this deletion, as there is insufficient space
                        self.padding = 0
                        continue
                    else:
                        self.padding -= variant_to_apply.length
                    alternate = self.read_sequence[position]
                else:
                    reference_length = variant_to_apply.get_ref_len()
                    alternate = variant_to_apply.get_alt()

                # Replace the entire ref with the entire alt
                mutated_sequence = \
                    mutated_sequence[:position] + \
                    alternate + \
                    mutated_sequence[position + reference_length:]

                self.update_quality_array(
                    reference_length,
                    alternate,
                    position,
                    "mutation",
                    quality_scores,
                    qual_score
                )

        # Update the read sequence with the applied mutations
        self.read_sequence = Seq(mutated_sequence)

    def apply_variants_for_final_output(
            self,
            quality_model: TraditionalQualityModel,
            rng: Generator
    ):
        """
        Gets mutated sequence to output for fastq/bam

        :param quality_model: The error model for the run
        :param rng: the random number generator for the run
        :return: the mutated sequence
        """
        # I realize that it's a little weird to convert self.read_sequence to mutable then assign to a variable
        # instead of operating on it in place, but while it is mutable, it was easier to treat it like a variable then
        # reconvert and reassign.
        if self.mutations:
            self.apply_mutations(list(quality_model.quality_scores), rng)
        if self.errors:
            self.apply_errors(quality_model)

        # The segments we hold off truncating because we need them for alignments,
        # but the quality array is fine to trim here. Trim to the genomic length: any adapter
        # tail appends its own scores afterwards, and equals run_read_length without one.
        self.quality_array = self.quality_array[:self.genomic_length]

    def contains(self, test_pos: int):
        return self.position <= test_pos < self.end_point

    def calculate_flags(self, paired_ended_run):
        """
        Calculates the flags for the read

        :param paired_ended_run: Whether the entire run was done in paired-ended mode
        """
        flag = 0
        if paired_ended_run:
            flag += 1
            if self.is_paired:
                # Whether this read has a mapped pair (proper pair)
                flag += 2
            # Flag 4 is if this read is unmapped, which isn't a situation we'll encounter in the simulation
            if not self.is_paired:
                # If this read's mate is unmapped (usually because it was off the end)
                flag += 8
            if self.is_reverse:
                # Flag to indicate this is the reverse strand
                flag += 16
            elif self.is_paired:
                # Flag that indicates that the mate is reversed
                # (which is always the case, if it exists, in this simulation)
                flag += 32
            if not self.is_reverse and self.is_paired:
                flag += 64
            if self.is_reverse and self.is_paired:
                flag += 128
            # None of the other potential samflags are relevant to this simulation
        return flag

    def finalize_read_and_write(
            self,
            err_model: SequencingErrorModel,
            qual_model: TraditionalQualityModel,
            fastq_handle,
            quality_offset: int,
            produce_fastq: bool,
            num_errors: int,
            rng: Generator,
            n_handling: str = "exclude",
    ):
        """
        Writes the record to the temporary fastq file

        :param err_model: The error model for the run
        :param qual_model: The quality score model for the run
        :param fastq_handle: for writing fastq1, either a gzip file or a bgzipWriter object.
        :param quality_offset: the quality offset for this run
        :param produce_fastq: If true, this will write out the temp fastqs. If false, this will only write out the tsams
            to create the bam files.
        :param num_errors: Estimated number of errors to add to this read.
        :param rng: the random number generator for this run
        :param n_handling: How to render residual 'N' bases ("exclude" -> literal low-quality 'N';
            "telomere" -> legacy low-quality TTAGGG fill). See Read.convert_masking.
        """

        # Generate quality scores for the read
        self.quality_array = qual_model.get_quality_scores(
            err_model.read_length,
            len(self.reference_segment),
            rng
        )

        # Render any 'N' bases in the reference segment: a literal low-quality 'N' base call
        # (default) or the legacy TTAGGG telomere fill. Updates the quality array in place.
        self.convert_masking(qual_model, n_handling)

        # Start the read sequence as an alias of the masked reference. Biopython Seq is
        # immutable; apply_mutations and apply_errors below produce new Seq objects via
        # their own working copies, so no independent deepcopy is needed here.
        self.read_sequence = self.reference_segment

        # Get errors for the read and update the quality score
        self.errors, self.padding = err_model.get_sequencing_errors(
            self.padding,
            self.reference_segment,
            self.quality_array,
            num_errors,
            rng
        )

        # This applies any variants, updates quality score and read sequence in place
        self.apply_variants_for_final_output(qual_model, rng)

        # If this read isn't low quality, pick a standard mapping quality
        # We could have this be user assigned.
        if not self.mapping_quality:
            self.mapping_quality = 70

        # Orient and truncate before building the quality string, so that any adapter tail is
        # appended to a read that is already in its final orientation and both the sequence and
        # the quality array include it.
        if self.is_reverse:
            self.read_sequence = self.read_sequence.reverse_complement()[:self.genomic_length]
        else:
            self.read_sequence = self.read_sequence[:self.genomic_length]

        if self.adapter_length:
            self._append_adapter_readthrough(err_model, qual_model, rng)

        self.read_quality_string = "".join([chr(x+33) for x in self.quality_array])
        # Might as well double check here
        if produce_fastq:
            fastq_record = f'@{self.name}\n{str(self.read_sequence)}\n+\n{self.read_quality_string}\n'
            fastq_handle.write(fastq_record)

        return len(self.errors)

    def _append_adapter_readthrough(
            self,
            err_model: SequencingErrorModel,
            qual_model: TraditionalQualityModel,
            rng: Generator
    ):
        """
        Pad a short-insert read out to its full length with 3' sequencing adapter.

        A sequencer runs a fixed number of cycles regardless of insert size, so when the insert is
        shorter than the read the polymerase reads off the end of the fragment and into the adapter
        ligated at the far end. This appends those bases to a read that is already in its final
        orientation, so the adapter lands at the 3' end where a trimmer expects it.

        Adapter bases:
          - are sourced cyclically, because a read can run past the end of the adapter and on into
            whatever follows it,
          - draw quality scores from the same model as genomic bases,
          - take substitution errors at the rate implied by those scores, so trimmers face
            realistic rather than pristine adapters. Insertion and deletion errors are deliberately
            not applied: they would change the read length, and the whole point of the padding is
            to reach exactly run_read_length,
          - carry no variants — adapter is not reference-derived — and are soft-clipped in the
            golden BAM by make_cigar.

        :param err_model: The sequencing error model for the run (supplies error rates and the
            substitution transition matrix).
        :param qual_model: The quality score model for the run.
        :param rng: The random number generator for this run.
        """
        number_of_bases = self.adapter_length
        scores = qual_model.get_quality_scores(err_model.read_length, number_of_bases, rng)

        bases = []
        for index, score in enumerate(scores):
            base = self.adapter_seq[index % len(self.adapter_seq)]
            # Phred definition, the same quality-derived rate get_sequencing_errors uses to place
            # errors on genomic bases. Computed here rather than read off a model lookup table so
            # this works for every quality model (the Markov one has no such table).
            error_rate = 10.0 ** (-float(score) / 10.0)
            if rng.random() < error_rate:
                nuc_index = NUC_IND.get(base)
                if nuc_index is not None:
                    base = str(rng.choice(ALLOWED_NUCL, p=err_model.transition_matrix[nuc_index]))
            bases.append(base)

        self.read_sequence = self.read_sequence + Seq("".join(bases))
        self.quality_array = np.concatenate(
            (self.quality_array, np.asarray(scores, dtype=int))
        )

    def convert_masking(self, quality_model: TraditionalQualityModel, n_handling: str = "exclude"):
        """
        Render 'N' (unknown) bases in this read's reference segment to floor quality.

        Two policies:
          - "exclude" (default): keep the 'N' as a literal base call and drop its quality to the
            model floor. Real sequencers emit 'N' for no-call positions, and downstream aligners
            and callers treat them as no-information rather than mismatches. Reads lying mostly
            inside an N run have already been dropped at placement time (see
            generate_reads._filter_n_regions), so only edge N's reach here.
          - "telomere": legacy behavior — replace each 'N' with a base from the generic human
            telomere repeat (TTAGGG) at floor quality. Fabricates mappable sequence; retained
            only for reproducing older runs.

        In both cases the quality score at each masked position is set to the model minimum.

        :param quality_model: The quality model for this run (supplies the floor score).
        :param n_handling: "exclude" (literal 'N') or "telomere" (TTAGGG fill).
        """
        bad_score = min(quality_model.quality_scores)
        # Generic human telomere repeat, used only by the legacy "telomere" policy.
        repeat_bases = list("TTAGGG")
        # Immutable Biopython Seq; the MutableSeq below is the working copy, so no
        # deepcopy needed here.
        raw_sequence = self.reference_segment

        start = raw_sequence.find('N')
        if start != -1:
            modified_segment = MutableSeq(raw_sequence[:start])
            for i in range(start, len(raw_sequence)):
                base = raw_sequence[i]
                if base in ALLOWED_NUCL:
                    modified_segment += base
                else:
                    # Either render a literal 'N' (default) or the legacy telomere fill;
                    # both sit at floor quality so callers can down-weight them.
                    modified_segment += 'N' if n_handling != "telomere" else repeat_bases[i % 6]
                    self.quality_array[i] = bad_score
        else:
            modified_segment = MutableSeq(raw_sequence)

        self.reference_segment = Seq(modified_segment)

    def make_cigar(self):
        """
        Build the CIGAR string describing how this read aligns to its reference window.

        Three paths, in priority order:
          1. No indels (the common case, ~98% of reads on default error models) — the CIGAR
             is just `{run_read_length}M`.
          2. Forward read whose indels all come from sequencing errors — walk the sorted
             error positions in O(read length) to emit M/I/D ops directly. No alignment
             needed; each error's stored location is already the anchor position in
             reference-window coordinates.
          3. Anything else (reverse reads with indels, or any read where a mutation indel
             may have been applied) — fall back to pairwise alignment. Mutation indels are
             applied before sequencing errors and can shift the read coordinate frame, and
             reverse reads truncate the segment from the opposite end; neither case fits
             the simple walker.

        Any 3' adapter tail is then soft-clipped on, since those bases are not reference-derived
        and must consume no reference coordinates. See _add_adapter_soft_clip for why its position
        in the string depends on the strand.

        :return: The CIGAR string for this read
        """
        return self.make_alignment()[0]

    def make_alignment(self):
        """
        Build the CIGAR string together with the reference position it starts from.

        The two come back as a pair because they are not independent. When an indel straddles the
        edge of the read, the alignment consumes reference before the read's first base; SAM cannot
        express that as a leading D, so POS carries it instead. A CIGAR handed out without its
        matching POS is not enough to place the read.

        :return: A (cigar, reference start) pair, the reference start being 0-based
        """
        error_indels = [
            e for e in self.errors
            if e.error_type is Insertion or e.error_type is Deletion
        ]
        has_mutation_indels = any(
            type(v) is Insertion or type(v) is Deletion
            for variants_at_loc in self.mutations.values()
            for v in variants_at_loc
        )

        if not error_indels and not has_mutation_indels:
            genomic_cigar, leading_skip = f"{self.genomic_length}M", 0
        elif not has_mutation_indels and not self.is_reverse:
            # The walker anchors on the first error's own location, so it never opens on a deletion.
            genomic_cigar, leading_skip = self._cigar_from_error_indels(error_indels), 0
        else:
            genomic_cigar, leading_skip = self._cigar_via_alignment()

        cigar = self._add_adapter_soft_clip(genomic_cigar)
        return cigar, self._reference_start(cigar, leading_skip)

    def _reference_start(self, cigar: str, leading_skip: int):
        """
        The reference position the CIGAR's first op aligns to — a BAM record's POS field.

        A forward read is anchored at its left edge: its deletion headroom comes from beyond the
        window, so an indel inside moves only where the read ends, and reference consumed ahead of
        the first base pushes the start to the right. A reverse read is anchored at its right edge
        instead. Its headroom is drawn from before the window and the reverse complement takes its
        bases from the right, so POS has to be found by stepping back from end_point over the
        reference the alignment covers. Reporting self.position for a reverse read shifts every
        gapped one by its net indel length.

        :param cigar: The CIGAR string for this read
        :param leading_skip: Reference bases the alignment consumed before the read's first base
        :return: The 0-based reference position for the record's POS field
        """
        if not self.is_reverse:
            return self.position + leading_skip
        return self.end_point - leading_skip - self.reference_span(cigar)

    def _add_adapter_soft_clip(self, genomic_cigar: str):
        """
        Attach the adapter tail to a genomic CIGAR as a soft clip.

        SAM stores SEQ in reference-forward orientation, and OutputFileWriter.write_bam_record
        reverse-complements a reverse read's sequence back to that orientation before writing. The
        CIGAR has to describe the same orientation, so the adapter — which is at the 3' end of the
        read as sequenced — appears at the *start* of the CIGAR for a reverse read and at the end
        for a forward one. Getting this backwards yields a BAM that passes samtools quickcheck
        while misplacing every short-insert reverse read.
        """
        if not self.adapter_length:
            return genomic_cigar
        if self.is_reverse:
            return f"{self.adapter_length}S{genomic_cigar}"
        return f"{genomic_cigar}{self.adapter_length}S"

    def _cigar_from_error_indels(self, error_indels):
        """
        Build the CIGAR for a forward read whose only indels come from sequencing errors.

        Walks the error list in reference-window order, emitting M/I/D ops and stopping
        once the CIGAR's query side reaches genomic_length (== run_read_length unless a 3'
        adapter tail occupies the rest of the read). Run-length-encodes the result as it goes.
        """
        events = sorted(error_indels, key=lambda e: e.location)

        ops: list[list] = []

        def emit(op_char, count):
            if count <= 0:
                return
            if ops and ops[-1][0] == op_char:
                ops[-1][1] += count
            else:
                ops.append([op_char, count])

        ref_pos = 0
        remaining_query = self.genomic_length

        for ev in events:
            if remaining_query == 0:
                break
            # M's leading up to and including the anchor base at ev.location.
            m_count = ev.location - ref_pos + 1
            m_emitted = min(m_count, remaining_query)
            emit('M', m_emitted)
            remaining_query -= m_emitted
            ref_pos = ev.location + 1
            if remaining_query == 0:
                break
            if ev.error_type is Insertion:
                i_emitted = min(ev.length, remaining_query)
                emit('I', i_emitted)
                remaining_query -= i_emitted
            else:  # Deletion
                emit('D', ev.length)
                ref_pos += ev.length

        if remaining_query > 0:
            emit('M', remaining_query)

        return ''.join(f"{count}{op}" for op, count in ops)

    def _cigar_via_alignment(self):
        """
        Pairwise-alignment fallback for cases the direct walker cannot model: reverse reads
        with indels, or any read where a mutation indel preceded the sequencing errors.

        The template is the read's reference window followed by the deletion headroom drawn beyond
        it (see generate_reads). A reverse read's window sits at the *end* of its segment, so
        reverse-complementing puts it at the front — which means that for either strand the query
        aligns at the start of the template and the headroom trails, and one walk handles both.

        The ops come from the alignment's own columns. Deriving them from read coordinates instead
        does not work: the aligned rows are longer than the read whenever there is a gap, so read
        offsets stop addressing the columns they are meant to, and an insertion longer than the
        read has no read coordinate to be recorded at.
        """
        template = self.reference_segment
        if self.is_reverse:
            template = template.reverse_complement()
        # Align only the reference-derived prefix; the adapter tail has no template to align to
        # and is soft-clipped by the caller.
        query = self.read_sequence[:self.genomic_length]

        aligner = PairwiseAligner()
        aligner.mode = "global"
        # Gaps have to cost something, and the two directions do not cost the same. On the default
        # scoring (every gap free) the aligner takes a gap to buy a single match, which renders one
        # indel as a scatter of 1 bp ops; with a flat affine penalty in both directions it instead
        # explains a long insertion as a wall of mismatches. The asymmetry below follows what NEAT
        # can actually produce.
        aligner.match_score = 1.0
        aligner.mismatch_score = -1.0
        # An inserted allele can run to hundreds of bases, so opening an insertion is what costs;
        # extending one is free.
        aligner.target_open_gap_score = -8.0
        aligner.target_extend_gap_score = 0.0
        # A deletion can only consume the headroom drawn beyond the read, so it stays short and
        # keeps a per-base price.
        aligner.query_open_gap_score = -5.0
        aligner.query_extend_gap_score = -1.0
        # The headroom past the read's last base is template the read never reached, so trailing
        # query gaps are free. The leading edge keeps its price: the read's first base comes from
        # template[0] on either strand, and a free gap there would let the alignment slide off the
        # anchor that POS is derived from. Assigned after the scores above, which would cover these.
        aligner.query_right_open_gap_score = 0.0
        aligner.query_right_extend_gap_score = 0.0

        alignment = aligner.align(template, query)[0]
        aligned_template = alignment[0]
        aligned_query = alignment[1]

        ops = []
        query_used = 0
        leading_skip = 0
        for template_base, query_base in zip(aligned_template, aligned_query):
            if query_used == self.genomic_length:
                # Everything past the read's last base is headroom, not part of its alignment.
                break
            if template_base == '-':
                ops.append('I')
                query_used += 1
            elif query_base == '-':
                if query_used:
                    ops.append('D')
                else:
                    # Reference consumed before the read's first base, which happens when an indel
                    # straddles the edge of the read. SAM has no leading D, so this is handed to
                    # POS instead of the CIGAR (see _reference_start).
                    leading_skip += 1
            else:
                ops.append('M')
                query_used += 1

        if not ops:
            # No alignment to describe (an empty read); M keeps the record well formed.
            return f"{self.genomic_length}M", 0

        if self.is_reverse:
            # Built against the reverse-complemented template, so these run in read order, while
            # SAM wants them in reference-forward order.
            ops.reverse()
        return self.tally_cigar_list(ops), leading_skip

    @staticmethod
    def reference_span(cigar: str):
        """
        How many reference bases a CIGAR consumes. M and D advance the reference; I and S are
        query-only.

        :param cigar: The CIGAR string to measure
        :return: The number of reference bases the alignment covers
        """
        span = 0
        count = ""
        for char in cigar:
            if char.isdigit():
                count += char
            else:
                if char in "MD":
                    span += int(count)
                count = ""
        return span

    @staticmethod
    def tally_cigar_list(cigar: list):
        cigar_string = ""
        cigar_char = cigar[0]
        char_count = 1
        for char in cigar[1:]:
            if char == cigar_char:
                char_count += 1
            else:
                cigar_string += str(char_count)
                cigar_string += cigar_char
                cigar_char = char
                char_count = 1
        cigar_string += str(char_count)
        cigar_string += cigar_char
        return cigar_string

    def get_mpos(self):
        """
        Get the mate position of the read
        """
        if self.is_paired:
            if self.is_reverse:
                return self.raw_read[0]
            else:
                return self.raw_read[2]
        else:
            return 0

    def get_tlen(self):
        """
        Get the template length for the read
        """
        if self.is_paired:
            length = self.raw_read[3] - self.raw_read[0] + 1
            if length < 0:
                return 0
            else:
                if self.is_reverse:
                    return -length
                else:
                    return length
        else:
            return 0
