name: Paper PDF

on:
  push:
    branches:
      - paper
  workflow_dispatch:

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Open Journals PDF Generator
        uses: openjournals/openjournals-draft-action@v1
        with:
          journal: joss
          paper-path: paper.md

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf

      - name: Debug list files
        run: ls -R